### ISSUE TITLE
Textbox focus

### ISSUE THREAD

**Issue by vmiwouter** [AvaloniaUI/Avalonia.Xaml.Behaviors#131]
Since rc1 cant focus a textbox anymore:

`System.ArgumentException: 'Cannot find method named Focus on object of type Avalonia.Controls.TextBox that matches the expected signature.'`

xaml:
`			
<TextBox x:Name="txtUsername" Margin="3" Text="{Binding Username}" TabIndex="1">
				<i:Interaction.Behaviors>
					<ia:EventTriggerBehavior EventName="Loaded">
						<ia:CallMethodAction TargetObject="{Binding ElementName=txtUsername}" MethodName="Focus"/>
					</ia:EventTriggerBehavior>
				</i:Interaction.Behaviors>
			</TextBox>
`

Via code behind it still works:
`            txtUsername.Loaded += OnActivated;

            void OnActivated(object? sender, RoutedEventArgs e)
            {
                txtUsername.Focus();
            }`

**Comment by wieslawsoltes** [comment]
It's because Focus method in avalonia now requires additional arguments. So CallMethodAction will not work this way.

**Comment by wieslawsoltes** [comment]
You can use FocusControlAction, I've added TargetControl support.
