### ISSUE TITLE
Microsoft.NETFramework.ReferenceAssemblies included as dependency

### ISSUE THREAD

**Issue by VMelnalksnis** [AvaloniaUI/Avalonia.Xaml.Behaviors#133]
In the latest v11.0.0 release `Microsoft.NETFramework.ReferenceAssemblies` is included as a dependency for the NuGet package, and I guess it's not inteded. I see that in #130 `PrivateAssets="All"` was added in `Directory.Packages.props`, but I think it's only respected in `PackageReference`, not `PackageVersion`.

**Comment by wieslawsoltes** [comment]
Fixed in v11.0.0.1
